#! /bin/bash

sxhkd -c ~/.config/sxhkd/sxhkdrc &
numlockx &
picom --config ~/.config/picom/picom.conf &
~/.config/scripts/launch_polybar.sh &
feh --bg-center Pictures/Wallpapers/wallhaven-zywgxy.jpg &

#firefox &
telegram-desktop -startintray &

bspc rule -a TelegramDesktop follow=off desktop='^3'
bspc rule -a firefox state=tiled DEsktop='^1'
bspc rule -a dmenu rectangle=900x22+610+90

bspc monitor -d 󰖟  󰳫   󰊗 

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
